#build stage
FROM rwynn/monstache-builder-base:0.0.1

# https://github.com/kelseyhightower/confd/issues/609
# ENV CGO_ENABLED=0

# ENV GOPATH /go

# RUN apk add --no-cache gcc go git musl-dev make zip

WORKDIR /go/src/app

COPY . .

RUN go get -d -v ./...

# # RUN go install -v ./...
RUN go install

# RUN go build
RUN make
