FROM rwynn/monstache-builder:1.0.0 AS build-app
# FROM rwynn/monstache-builder-cache:1.0.0 AS build-app

WORKDIR /go/src/app

COPY . .

RUN go get -d -v ./...

# RUN make release

# RUN ln -s build/linux-amd64/monstache monstache
